// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzGiaJoAjS3nf3wp2-e_7gcVPqhVHFSuw',
    appId: '1:930936218296:web:871c80e2a427c76f78ca4d',
    messagingSenderId: '930936218296',
    projectId: 'todo-firebase-crud-24f77',
    authDomain: 'todo-firebase-crud-24f77.firebaseapp.com',
    storageBucket: 'todo-firebase-crud-24f77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRD2ztOfsK0gbJcq2eABHr7l-YJewvP_g',
    appId: '1:930936218296:android:8e365537c3902a0878ca4d',
    messagingSenderId: '930936218296',
    projectId: 'todo-firebase-crud-24f77',
    storageBucket: 'todo-firebase-crud-24f77.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi_ixm9zrUmzQAo_nyjIQ5MK3vwK9y4pY',
    appId: '1:930936218296:ios:0a8c67b9372402c778ca4d',
    messagingSenderId: '930936218296',
    projectId: 'todo-firebase-crud-24f77',
    storageBucket: 'todo-firebase-crud-24f77.appspot.com',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_ixm9zrUmzQAo_nyjIQ5MK3vwK9y4pY',
    appId: '1:930936218296:ios:0a8c67b9372402c778ca4d',
    messagingSenderId: '930936218296',
    projectId: 'todo-firebase-crud-24f77',
    storageBucket: 'todo-firebase-crud-24f77.appspot.com',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzGiaJoAjS3nf3wp2-e_7gcVPqhVHFSuw',
    appId: '1:930936218296:web:81d502d62465816478ca4d',
    messagingSenderId: '930936218296',
    projectId: 'todo-firebase-crud-24f77',
    authDomain: 'todo-firebase-crud-24f77.firebaseapp.com',
    storageBucket: 'todo-firebase-crud-24f77.appspot.com',
  );

}